POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Kukko100",
    "title": "kukon tarinat2",
    "url": "www.google.com",
    "likes": 1,
    "userId": "648afd7c0ce49d164abb38b3"

}